/* Desktop Quest 0.2a — all wording lives here. English is the key, Spanish is the value. */
window.ES = {
  /* start screen */
  'Mission: Linux':'Misión: Linux',
  'Desktop Quest 0.2a — walk inside the Linux desktop':'Aventura del Escritorio 0.2a — camina dentro del escritorio de Linux',
  'This world is built like your real screen. The <b>icons</b> are up in the top-left, the <b>App Launcher</b> gate is at the bottom, and the <b>system menu</b> tower is in the top-right — exactly where they are on the computer in front of you.':'Este mundo está hecho como tu pantalla real. Los <b>iconos</b> están arriba a la izquierda, la puerta del <b>Lanzador de Apps</b> está abajo y la torre del <b>menú del sistema</b> está arriba a la derecha — igual que en la computadora que tienes enfrente.',
  'Start the mission ▶':'Empezar la misión ▶',
  'Click the screen to look around with the mouse. Press Esc to let the mouse go.':'Haz clic en la pantalla para mirar con el ratón. Presiona Esc para soltar el ratón.',
  'Move':'Moverse','Turn':'Girar','Look':'Mirar','Select':'Escoger','Open':'Abrir','Run':'Correr',
  'W A S D or ↑ ↓':'W A S D o ↑ ↓','← → or mouse':'← → o el ratón','move the mouse':'mueve el ratón',
  'one click':'un clic','double-click':'doble clic','hold Shift':'mantén Shift',
  /* --- code console --- */
  'CODE CONSOLE':'CONSOLA DE CÓDIGO','BLOCKS':'BLOQUES','YOUR PROGRAM':'TU PROGRAMA',
  'YOUR CODE SAYS':'TU CÓDIGO DICE','Clear':'Borrar','▶ RUN':'▶ EJECUTAR','RUNNING':'EJECUTANDO',
  'repeat':'repite','times':'veces','put blocks here':'pon bloques aquí',
  'Your program is empty. Click a block on the left.':'Tu programa está vacío. Haz clic en un bloque de la izquierda.',
  'Click a block to add it. Click a repeat to put blocks inside it.':'Haz clic en un bloque para agregarlo. Haz clic en un “repite” para poner bloques adentro.',
  'New blocks go INSIDE the repeat. Click the repeat again to stop.':'Los bloques nuevos van ADENTRO del “repite”. Haz clic otra vez para salir.',
  'Add at least one shoot() block first.':'Primero agrega un bloque shoot().',
  'Fire one shot where you are aiming':'Dispara una vez a donde apuntas',
  'Pause for a moment':'Espera un momento',
  'Do the blocks inside, again and again':'Hace los bloques de adentro, una y otra vez',
  'open the code console':'abrir la consola de código',
  /* --- mission 1 --- */
  'Mission 1 — Loops':'Misión 1 — Bucles','The Loop Chamber':'La Cámara del Bucle',
  'MISSION 1':'MISIÓN 1',
  'Program one shot':'Programa un disparo','Clear three drones':'Elimina tres drones',
  'Clear five drones':'Elimina cinco drones','Beat THE LOOPER':'Vence a EL REPETIDOR',
  'Clear the drones':'Elimina los drones',
  'Your gun runs your <b>program</b>. Open the console with <b>C</b>, add one <b>shoot()</b> block, and press RUN.':'Tu arma ejecuta tu <b>programa</b>. Abre la consola con <b>C</b>, agrega un bloque <b>shoot()</b> y presiona EJECUTAR.',
  'Three of them. You could add three <b>shoot()</b> blocks… or use a <b>repeat</b> block and put one shoot inside it.':'Son tres. Puedes agregar tres bloques <b>shoot()</b>… o usar un bloque <b>repite</b> y poner un shoot adentro.',
  'Five now. Set the <b>repeat</b> number to 5 and keep one <b>shoot()</b> inside it. Aim at a new drone each time.':'Ahora son cinco. Pon el número del <b>repite</b> en 5 y deja un <b>shoot()</b> adentro. Apunta a un dron distinto cada vez.',
  '<b>THE LOOPER</b> has an 8-part shield that grows back after every program. One shot at a time will never win — <b>repeat 8</b> in a single program will.':'<b>EL REPETIDOR</b> tiene un escudo de 8 partes que se regenera después de cada programa. Un disparo a la vez nunca gana — <b>repite 8</b> en un solo programa sí.',
  'THE LOOPER: “Not enough! My shield grows back!”':'EL REPETIDOR: “¡No es suficiente! ¡Mi escudo se regenera!”',
  'Missed — put the crosshair on the target.':'Fallaste — pon la mira sobre el objetivo.',
  'Clear! Next wave…':'¡Listo! Siguiente oleada…',
  'MISSION 1 COMPLETE':'MISIÓN 1 COMPLETADA',
  'You beat THE LOOPER with a <b>loop</b>. One block, written once, ran again and again — that is what a loop is for.':'Venciste a EL REPETIDOR con un <b>bucle</b>. Un bloque, escrito una sola vez, se ejecutó una y otra vez — para eso sirve un bucle.',
  'The code you wrote':'El código que escribiste',
  /* --- combat, health, enemies --- */
  'HEALTH':'VIDA','You were knocked out!':'¡Te noquearon!',
  'Nothing is lost — the wave starts again. Try using cover: put a block between you and them.':'No pierdes nada — la oleada empieza otra vez. Usa las cubiertas: pon un bloque entre tú y ellos.',
  'Try again ▶':'Intentar otra vez ▶',
  'red':'rojo','blue':'azul',
  'That shield is {c} — use the {c} bolt!':'Ese escudo es {c} — ¡usa el disparo {c}!',
  'PRISM is {c} right now — check the colour first!':'PRISM está {c} ahora — ¡revisa el color primero!',
  '{n}: “Not enough! My shield grows back!”':'{n}: “¡No es suficiente! ¡Mi escudo se regenera!”',
  'THE LOOPER':'EL REPETIDOR','PRISM':'PRISMA','OFF-BY-ONE':'EL DESCUADRADO',
  /* --- missions --- */
  'Mission 1 — Loops':'Misión 1 — Bucles','Mission 2 — Choices':'Misión 2 — Decisiones',
  'Mission 3 — Functions':'Misión 3 — Funciones','COMPLETE':'COMPLETADA',
  'The Loop Chamber':'La Cámara del Bucle','The Prism Vault':'La Bóveda del Prisma',
  'The Off-By-One Foundry':'La Fundición del Descuadrado',
  'Break a red shield':'Rompe un escudo rojo','Break both colours':'Rompe los dos colores',
  'Survive the mixed wave':'Sobrevive la oleada mixta','Beat PRISM':'Vence a PRISMA',
  'Teach the gun a combo':'Enséñale un combo al arma','Use the combo on a wave':'Usa el combo en una oleada',
  'Clear the corridor':'Limpia el pasillo','Beat OFF-BY-ONE':'Vence a EL DESCUADRADO',
  'Three of them, and they shoot back now. Use a <b>repeat</b> block with one <b>shoot()</b> inside — and keep moving.':'Son tres, y ahora disparan de vuelta. Usa un bloque <b>repite</b> con un <b>shoot()</b> adentro — y sigue moviéndote.',
  'Five, including a slow <b>slugger</b> that hits hard. Set <b>repeat</b> to 5 and sweep your aim. Hide behind a block to heal.':'Cinco, incluido un <b>lento</b> que pega duro. Pon el <b>repite</b> en 5 y mueve la mira. Escóndete detrás de un bloque para curarte.',
  '<b>THE LOOPER</b> has an 8-part shield that grows back after every program. One shot at a time can never win — <b>repeat 8</b> in a single program can.':'<b>EL REPETIDOR</b> tiene un escudo de 8 partes que se regenera después de cada programa. Un disparo a la vez nunca gana — <b>repite 8</b> en un solo programa sí.',
  'These drones carry <b>coloured shields</b>. A red shield only breaks to a <b>red bolt</b>. Look at the ring, then pick the matching block.':'Estos drones tienen <b>escudos de colores</b>. Un escudo rojo solo se rompe con un <b>disparo rojo</b>. Mira el anillo y escoge el bloque que combina.',
  'Now both colours are here. Guessing wastes shots — use an <b>if</b> block: <i>if target is red → shootRed()</i>, and another for blue.':'Ahora están los dos colores. Adivinar gasta disparos — usa un bloque <b>si</b>: <i>si el objetivo es rojo → shootRed()</i>, y otro para el azul.',
  'A mixed wave with snipers watching from the back. Put your <b>if</b> blocks inside a <b>repeat</b> so every shot checks the colour first.':'Una oleada mixta con francotiradores al fondo. Pon tus bloques <b>si</b> adentro de un <b>repite</b> para que cada disparo revise el color primero.',
  '<b>PRISM</b> changes colour every two seconds. A fixed program cannot beat that — only <b>if</b> inside a <b>repeat</b> checks the colour every single shot.':'<b>PRISMA</b> cambia de color cada dos segundos. Un programa fijo no puede ganarle — solo un <b>si</b> adentro de un <b>repite</b> revisa el color en cada disparo.',
  'Put <b>shootRed()</b> and <b>shootBlue()</b> inside <b>define combo</b>. Then drop one <b>combo()</b> block to run both at once. Write it once, use it forever.':'Pon <b>shootRed()</b> y <b>shootBlue()</b> adentro de <b>define combo</b>. Luego usa un bloque <b>combo()</b> para hacer los dos de una vez. Escríbelo una vez y úsalo siempre.',
  'Six of them, in pairs. Keep your <b>combo</b> and call it inside a <b>repeat</b> — three calls, six shots.':'Son seis, en parejas. Guarda tu <b>combo</b> y llámalo adentro de un <b>repite</b> — tres llamadas, seis disparos.',
  'A corridor with cover on both sides and swarmers that rush you. Move through it — you cannot hit what you cannot see.':'Un pasillo con cubiertas de los dos lados y bichos que se te echan encima. Avanza — no puedes darle a lo que no ves.',
  '<b>OFF-BY-ONE</b> shows <b>7</b> shield parts but always has <b>one more</b> than he shows. Count carefully — programmers start counting at zero.':'<b>EL DESCUADRADO</b> muestra <b>7</b> partes de escudo pero siempre tiene <b>una más</b> de las que muestra. Cuenta con cuidado — los programadores empiezan a contar desde cero.',
  'You beat PRISM with an <b>if</b>. A program that checks before it acts can handle something that keeps changing.':'Venciste a PRISMA con un <b>si</b>. Un programa que revisa antes de actuar puede con algo que cambia todo el tiempo.',
  'You beat OFF-BY-ONE with a <b>function</b>. You taught the gun a move once and called it whenever you needed it — and you counted carefully.':'Venciste a EL DESCUADRADO con una <b>función</b>. Le enseñaste un movimiento al arma una vez y lo llamaste cuando lo necesitaste — y contaste con cuidado.',
  /* --- range + doors --- */
  'Firing Range':'Campo de Tiro','FIRING RANGE':'CAMPO DE TIRO','MISSION 2':'MISIÓN 2','MISSION 3':'MISIÓN 3',
  'Click the targets as fast as you can. This is pure aiming — no code. <b>Left click</b> to shoot.':'Dispara a los blancos lo más rápido que puedas. Esto es solo puntería — sin código. <b>Clic izquierdo</b> para disparar.',
  'Targets hit':'Blancos','Accuracy':'Precisión','Shots':'Disparos','Score':'Puntos',
  'Warm-up done. Faster hands, fewer wasted shots.':'Calentamiento listo. Manos más rápidas, menos disparos perdidos.',
  'Back to the desktop':'Volver al escritorio',
  '🔒 Locked. Finish {m} first.':'🔒 Cerrado. Primero termina {m}.',
  'the intro mission':'la misión de introducción','Mission 1':'la Misión 1','Mission 2':'la Misión 2',
  'done — play again':'terminada — juega otra vez',
  'Pick a mission door. Locked ones need the mission before them.':'Escoge una puerta de misión. Las cerradas necesitan la misión anterior.',
  /* --- new blocks --- */
  'if target is':'si el objetivo es','define combo':'define combo',
  'Fire a RED bolt — breaks red shields':'Dispara un rayo ROJO — rompe escudos rojos',
  'Fire a BLUE bolt — breaks blue shields':'Dispara un rayo AZUL — rompe escudos azules',
  'Only do the blocks inside IF it is true':'Hace los bloques de adentro SOLO si es verdad',
  'Run the blocks you put in DEFINE combo':'Ejecuta los bloques que pusiste en DEFINE combo',
  'Teach the gun a move once, then call it':'Enséñale un movimiento al arma una vez y llámalo',
  'Nice work, coder.':'Buen trabajo, programador.',
  /* HUD */
  'MISSION':'MISIÓN','DESKTOP MAP':'MAPA DEL ESCRITORIO',
  'icons ▪ launcher ▪ system menu':'iconos ▪ lanzador ▪ menú del sistema',
  'Basic Training — The Desktop':'Entrenamiento Básico — El Escritorio',
  'Nice work!':'¡Buen trabajo!',
  /* objects */
  'Files':'Archivos','Text Editor':'Editor de Texto','Paint':'Pintura','Trash':'Papelera',
  'Music':'Música','Photos':'Fotos','Pictures':'Imágenes','Documents':'Documentos','Home':'Inicio',
  'App Launcher':'Lanzador de Apps','System Menu':'Menú del Sistema','Close (✕)':'Cerrar (✕)',
  'icon':'icono','folder':'carpeta','gate':'puerta','tower':'torre','door':'puerta',
  'SELECTED':'ESCOGIDO','double-click to open':'doble clic para abrir','walk in':'entra caminando',
  /* objectives + briefings */
  'Find the icons':'Encuentra los iconos',
  'Look to your <b>left</b> — those tall panels are the <b>icons</b>, in the same top-left corner they sit in on your real desktop.':'Mira a tu <b>izquierda</b> — esos paneles altos son los <b>iconos</b>, en la misma esquina de arriba a la izquierda donde están en tu escritorio real.',
  'Select the Files icon':'Escoge el icono Archivos',
  'Put the crosshair on the <b>Files</b> door and press the left button <b>one time</b>. One click only <b>chooses</b> it.':'Pon la mira en la puerta de <b>Archivos</b> y presiona el botón izquierdo <b>una vez</b>. Un clic solo lo <b>escoge</b>.',
  'Open Files with a double-click':'Abre Archivos con doble clic',
  'Now <b>two fast clicks</b> on the same door to <b>open</b> the app and walk inside.':'Ahora <b>dos clics rápidos</b> en la misma puerta para <b>abrir</b> la aplicación y entrar.',
  'Open the Pictures folder':'Abre la carpeta Imágenes',
  'You are inside <b>Files</b>. Folders are doors. <b>Double-click</b> the <b>Pictures</b> folder.':'Estás dentro de <b>Archivos</b>. Las carpetas son puertas. Haz <b>doble clic</b> en la carpeta <b>Imágenes</b>.',
  'Leave through the red ✕':'Sal por la ✕ roja',
  'To close an app you use the red <b>✕</b>. Find it and double-click it to get back to the desktop.':'Para cerrar una aplicación usas la <b>✕</b> roja. Encuéntrala y haz doble clic para volver al escritorio.',
  'Reach the App Launcher':'Llega al Lanzador de Apps',
  'Walk to the big gate at the <b>bottom</b> of the desktop. That is the <b>App Launcher</b> — every app lives behind it.':'Camina hasta la puerta grande de <b>abajo</b> del escritorio. Ese es el <b>Lanzador de Apps</b> — todas las aplicaciones viven ahí.',
  'Read the system menu':'Lee el menú del sistema',
  'Go to the tower in the <b>top-right</b> and read the <b>battery</b> number out loud. That corner holds Wi-Fi, volume, battery and the clock.':'Ve a la torre de <b>arriba a la derecha</b> y lee el número de la <b>batería</b> en voz alta. Esa esquina tiene el Wi-Fi, el volumen, la batería y el reloj.',
  'Battery: {n}%':'Batería: {n}%',
  'Wi-Fi: connected':'Wi-Fi: conectado','Volume: {n}%':'Volumen: {n}%','Clock: {t}':'Reloj: {t}',
  /* flat transfer */
  'Now do it for real':'Ahora hazlo de verdad',
  'This is the flat desktop — the one on your screen. Same job: <b>double-click</b> Files, then close it with the red <b>✕</b>.':'Este es el escritorio plano — el de tu pantalla. El mismo trabajo: <b>doble clic</b> en Archivos y ciérralo con la <b>✕</b> roja.',
  'One click chooses. Two fast clicks open.':'Un clic escoge. Dos clics rápidos abren.',
  'Now close it with the red ✕.':'Ahora ciérralo con la ✕ roja.',
  'Linux Lab — Desktop':'Laboratorio Linux — Escritorio',
  'This is the Desktop':'Esto es el Escritorio',
  /* end */
  'Mission complete!':'¡Misión cumplida!',
  'You walked the desktop, opened an app, went into a folder, closed a window with the ✕, found the App Launcher and read the system menu — then did it again on the flat desktop.':'Caminaste por el escritorio, abriste una aplicación, entraste a una carpeta, cerraste una ventana con la ✕, encontraste el Lanzador de Apps y leíste el menú del sistema — y luego lo hiciste otra vez en el escritorio plano.',
  'Play again':'Jugar otra vez',
  'Clicks':'Clics','Double-clicks':'Dobles clics','Time':'Tiempo','Steps walked':'Pasos caminados'
};
window.LANG = 'en';
function t(s,p){
  let out = (window.LANG==='es' && window.ES[s]!==undefined) ? window.ES[s] : s;
  if(p) for(const k in p) out = out.split('{'+k+'}').join(p[k]);
  return out;
}
